import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress'
import { RefreshCcw, Download, TrendingUp, Users, ShoppingCart, Package, AlertTriangle } from 'lucide-react'
import { jsPDF } from 'jspdf'
import { useAuth } from '../App'
import apiService from '../services/api'

const currency = new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 })

const getRoleValue = (role) => {
  if (!role) return ''
  return role.toString().toUpperCase().replace(/\s+/g, '_')
}

const AnalyticsPage = () => {
  const { user, logout } = useAuth()
  const [loading, setLoading] = useState(true)
  const [syncing, setSyncing] = useState(false)
  const [error, setError] = useState('')
  const [listings, setListings] = useState([])
  const [orders, setOrders] = useState([])
  const [messages, setMessages] = useState([])

  const isAdmin = getRoleValue(user?.role) === 'ADMIN'

  const isAuthError = (message) =>
    typeof message === 'string' &&
    (message.includes('expired') || message.includes('Invalid') || message.includes('token') || message.includes('401'))

  const loadAnalytics = async () => {
    setError('')
    setSyncing(true)
    try {
      const [listingsResponse, ordersResponse, messagesResponse] = await Promise.all([
        apiService.getListings({ limit: 200 }).catch((err) => ({ success: false, _error: err.message })),
        apiService.getOrders().catch((err) => ({ success: false, _error: err.message })),
        apiService.getMessages().catch((err) => ({ success: false, _error: err.message }))
      ])

      const authFailure = [listingsResponse, ordersResponse, messagesResponse].find(
        (res) => !res.success && isAuthError(res._error)
      )

      if (authFailure) {
        // Token is expired — clear stale auth state so ProtectedRoute
        // redirects to /login and returns here after a fresh sign-in.
        logout()
        return
      }

      if (listingsResponse?.success) {
        setListings(listingsResponse.data?.listings || [])
      }

      if (ordersResponse?.success) {
        setOrders(ordersResponse.data?.orders || [])
      }

      if (messagesResponse?.success) {
        setMessages(messagesResponse.data?.messages || [])
      }
    } catch (loadError) {
      if (isAuthError(loadError.message)) {
        logout()
      } else {
        setError(loadError.message || 'Failed to load analytics data')
      }
    } finally {
      setLoading(false)
      setSyncing(false)
    }
  }

  useEffect(() => {
    loadAnalytics()
  }, [])

  const metrics = useMemo(() => {
    const totalRevenue = orders.reduce((sum, order) => sum + (order.totalAmount || 0), 0)
    const sellers = new Set(listings.map((listing) => listing.farmer?.id).filter(Boolean))
    const buyers = new Set(orders.map((order) => order.buyer?.id || order.buyerId).filter(Boolean))

    const ordersByStatus = orders.reduce((accumulator, order) => {
      const key = order.status || 'UNKNOWN'
      accumulator[key] = (accumulator[key] || 0) + 1
      return accumulator
    }, {})

    const listingsByCategory = listings.reduce((accumulator, listing) => {
      const key = listing.category || 'Uncategorized'
      accumulator[key] = (accumulator[key] || 0) + 1
      return accumulator
    }, {})

    const topCategories = Object.entries(listingsByCategory)
      .sort((left, right) => right[1] - left[1])
      .slice(0, 5)

    const conversionRate = listings.length ? Math.min(100, Math.round((orders.length / listings.length) * 100)) : 0

    const avgOrderValue = orders.length ? totalRevenue / orders.length : 0

    return {
      totalRevenue,
      activeSellers: sellers.size,
      activeBuyers: buyers.size,
      totalOrders: orders.length,
      totalListings: listings.length,
      totalMessages: messages.length,
      conversionRate,
      avgOrderValue,
      ordersByStatus,
      topCategories
    }
  }, [listings, orders, messages])

  const exportSnapshot = () => {
    const doc = new jsPDF()
    const dateLabel = new Date().toISOString().split('T')[0]
    const leftMargin = 14

    doc.setFontSize(16)
    doc.text('FarmConnect Analytics Snapshot', leftMargin, 16)

    doc.setFontSize(10)
    doc.text(`Generated: ${new Date().toLocaleString()}`, leftMargin, 24)
    doc.text(`Generated by: ${user?.email || 'Unknown Admin'}`, leftMargin, 30)

    let y = 40
    doc.setFontSize(12)
    doc.text('Key Metrics', leftMargin, y)
    y += 8

    doc.setFontSize(10)
    const lines = [
      `Gross Platform Revenue: ${currency.format(metrics.totalRevenue)}`,
      `Active Buyers: ${metrics.activeBuyers}`,
      `Active Sellers: ${metrics.activeSellers}`,
      `Total Listings: ${metrics.totalListings}`,
      `Total Orders: ${metrics.totalOrders}`,
      `Average Order Value: ${currency.format(metrics.avgOrderValue)}`,
      `Tracked Messages: ${metrics.totalMessages}`,
      `Order Conversion: ${metrics.conversionRate}%`
    ]

    lines.forEach((line) => {
      doc.text(line, leftMargin, y)
      y += 6
    })

    y += 4
    doc.setFontSize(12)
    doc.text('Orders by Status', leftMargin, y)
    y += 8
    doc.setFontSize(10)

    const statusEntries = Object.entries(metrics.ordersByStatus)
    if (statusEntries.length === 0) {
      doc.text('No orders available.', leftMargin, y)
      y += 6
    } else {
      statusEntries.forEach(([status, count]) => {
        doc.text(`${status}: ${count}`, leftMargin, y)
        y += 6
      })
    }

    y += 4
    doc.setFontSize(12)
    doc.text('Top Product Categories', leftMargin, y)
    y += 8
    doc.setFontSize(10)

    if (metrics.topCategories.length === 0) {
      doc.text('No listing categories available.', leftMargin, y)
    } else {
      metrics.topCategories.forEach(([category, count]) => {
        if (y > 280) {
          doc.addPage()
          y = 20
        }
        doc.text(`${category}: ${count} listings`, leftMargin, y)
        y += 6
      })
    }

    doc.save(`farmconnect-analytics-${dateLabel}.pdf`)
  }

  if (!isAdmin) {
    return (
      <div className="min-h-screen bg-gray-50 p-6">
        <Card className="max-w-2xl mx-auto">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-red-700">
              <AlertTriangle className="h-5 w-5" />
              Administrator Access Required
            </CardTitle>
            <CardDescription>
              This page is only available to system administrators with platform-wide visibility.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Link to="/dashboard">
              <Button variant="outline">Return to Dashboard</Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 flex flex-wrap items-center justify-between gap-3">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Platform Analytics</h1>
            <p className="text-gray-600">System-wide performance and activity visibility across all users and accounts.</p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={loadAnalytics} disabled={syncing}>
              <RefreshCcw className={`h-4 w-4 mr-2 ${syncing ? 'animate-spin' : ''}`} />
              Refresh
            </Button>
            <Button onClick={exportSnapshot}>
              <Download className="h-4 w-4 mr-2" />
              Export Snapshot
            </Button>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        {error && <p className="text-red-600 text-sm">{error}</p>}

        {loading ? (
          <Card>
            <CardContent className="py-8 text-center text-gray-600">Loading analytics...</CardContent>
          </Card>
        ) : (
          <>
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
              <Card>
                <CardContent className="p-5">
                  <p className="text-sm text-gray-500">Gross Platform Revenue</p>
                  <p className="text-2xl font-semibold mt-2">{currency.format(metrics.totalRevenue)}</p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-5">
                  <p className="text-sm text-gray-500">Active Buyers</p>
                  <p className="text-2xl font-semibold mt-2">{metrics.activeBuyers}</p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-5">
                  <p className="text-sm text-gray-500">Active Sellers</p>
                  <p className="text-2xl font-semibold mt-2">{metrics.activeSellers}</p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-5">
                  <p className="text-sm text-gray-500">Order Conversion</p>
                  <p className="text-2xl font-semibold mt-2">{metrics.conversionRate}%</p>
                  <Progress value={metrics.conversionRate} />
                </CardContent>
              </Card>
            </div>

            <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <ShoppingCart className="h-4 w-4" />
                    Orders by Status
                  </CardTitle>
                  <CardDescription>Live distribution of all platform orders.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-3">
                  {Object.keys(metrics.ordersByStatus).length === 0 ? (
                    <p className="text-sm text-gray-500">No orders available.</p>
                  ) : (
                    Object.entries(metrics.ordersByStatus).map(([status, count]) => (
                      <div key={status} className="flex items-center justify-between text-sm">
                        <Badge className="bg-gray-100">{status}</Badge>
                        <span className="font-medium">{count}</span>
                      </div>
                    ))
                  )}
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Package className="h-4 w-4" />
                    Top Product Categories
                  </CardTitle>
                  <CardDescription>Most active listing categories across all accounts.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-3">
                  {metrics.topCategories.length === 0 ? (
                    <p className="text-sm text-gray-500">No listing categories available.</p>
                  ) : (
                    metrics.topCategories.map(([category, count]) => (
                      <div key={category} className="flex items-center justify-between text-sm">
                        <span>{category}</span>
                        <Badge className="bg-green-100 text-green-700">{count} listings</Badge>
                      </div>
                    ))
                  )}
                </CardContent>
              </Card>
            </div>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-4 w-4" />
                  Administrative Performance Summary
                </CardTitle>
                <CardDescription>Consolidated operational insights for platform-wide decision making.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
                  <div className="p-4 border rounded-lg">
                    <p className="text-sm text-gray-500">Total Listings</p>
                    <p className="font-semibold text-xl mt-1">{metrics.totalListings}</p>
                  </div>
                  <div className="p-4 border rounded-lg">
                    <p className="text-sm text-gray-500">Total Orders</p>
                    <p className="font-semibold text-xl mt-1">{metrics.totalOrders}</p>
                  </div>
                  <div className="p-4 border rounded-lg">
                    <p className="text-sm text-gray-500">Average Order Value</p>
                    <p className="font-semibold text-xl mt-1">{currency.format(metrics.avgOrderValue)}</p>
                  </div>
                  <div className="p-4 border rounded-lg">
                    <p className="text-sm text-gray-500">Tracked Messages</p>
                    <p className="font-semibold text-xl mt-1">{metrics.totalMessages}</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Users className="h-4 w-4" />
                  Recent Platform Transactions
                </CardTitle>
                <CardDescription>Latest transactions affecting users, inventory, and revenue.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {orders.slice(0, 6).map((order) => (
                    <div key={order.id} className="border rounded-lg p-3 flex flex-wrap items-center justify-between gap-2">
                      <div>
                        <p className="font-medium text-sm">{order.listing?.title || 'Untitled Listing'}</p>
                        <p className="text-xs text-gray-500">
                          Buyer: {order.buyer?.firstName || 'Unknown'} {order.buyer?.lastName || ''}
                        </p>
                      </div>
                      <div className="text-right">
                        <Badge>{order.status}</Badge>
                        <p className="text-sm font-medium mt-1">{currency.format(order.totalAmount || 0)}</p>
                      </div>
                    </div>
                  ))}
                  {orders.length === 0 && <p className="text-sm text-gray-500">No transactions available.</p>}
                </div>
              </CardContent>
            </Card>
          </>
        )}
      </div>
    </div>
  )
}

export default AnalyticsPage
